export const actions = {
  CREATE_GAME: 'CREATE_GAME',
  CREATE_GAME_SUCCESS: 'CREATE_GAME_SUCCESS',
  CREATE_GAME_ERROR: 'CREATE_GAME_ERROR',
  SET_GAME_ID: 'SET_GAME_ID',
  RESET_GAME: 'RESET_GAME'
}
